### ISSUE TITLE
Evaluate resource ordering to ensure authn/authz cannot  be circumvented in failure modes

### ISSUE THREAD

**Issue by rjferguson21** [defenseunicorns/uds-core#519]
Blake pointed out that as we add authn/authz functionality within Istio via authservice we need to be mindful of how unexpected failures and in general resource ordering could potentially leave applications exposed.

A straightforward way we might be able to somewhat alleviate this would be applying authorization policies (keycloak + authservice functionality) before the Istio resource generation.  This would likely be an improvement for first reconciliation but we'd have to probably be more creative for cases where the `VirtualService` already existed.

"There is a potential security issue where this can fail open:

1. Create a Package without groups, and wait for UDS operator to create the VirtualService
2. Update the Package to have authservice (and optionally groups).
   * If the operator has an error during processing of either of these SSO functions, these functions will throw an error and halt the reconcile... but the old VirtualService will stay around. This means that it fails open.

(similarly you could go from Package+authservice → Package+authservice+groups and get an error in group application and get similar bad fail-open)

I'm unsure what the best solution is. Should we maybe catch errors in the authservice code and tear down the virtual services? That would mean the operator fails closed? Perhaps move `istioResources()` below this code and pass it a bool `destroy` option that triggers teardown (this allows better code reuse)?"

_Originally posted by @bburky in https://github.com/defenseunicorns/uds-core/pull/201#discussion_r1657844035_

**Comment by rjferguson21** [comment]
@bburky I believe part of the original comment related to the order of resources created by the operator was already addressed by our reordering initial creation of the Istio resources to happen after Keycloak/Authservice methods - see https://github.com/defenseunicorns/uds-core/blob/main/src/pepr/operator/reconcilers/package-reconciler.ts#L69-L73 

For the other concern, I have implemented over in https://github.com/defenseunicorns/uds-core/pull/804 some logic to temporarily remove a Package's VirtualServices and ServiceEntries in the event of any failure during reconciliation.  That logic is behind a feature flag at the moment to allow folks to opt into the behavior.  In some circumstances I could see it being disruptive (e.g. temporary failures would delete/recreate VirtualServices), but I think there is likely some appetite for the functionality but wanted to ensure it is worth it.

Discussing internally we had some reservations about introducing given it is primarily protecting users who are upgrading an existing Package that would have had a previously more permissive configuration (e.g. no operator enforced authz via the `groups:` or authservice protection).   I am kind of on the fence after implementing the draft PR on whether or not that circumstance is worth accounting for specifically at this point and might recommend we focus more so on general error handling improvements in reconciliation but wanted to get your take.   Maybe there are less destructive protections we can take.

See:
* https://github.com/defenseunicorns/uds-core/issues/502
* https://github.com/defenseunicorns/uds-core/issues/557

**Comment by bburky** [comment]
Maybe a simpler answer is to specifically move the AuthorizationPolicy up in the application order (before keycloak even)? Then on error, it fails closed... except you can't do that because we add the client name to the AutorizationPolicy.

Lets do an early apply of a default-deny authorization policy instead? (you'd still need the authservice selectors in it)
https://istio.io/latest/docs/ops/best-practices/security/#use-default-deny-patterns
See `allow-nothing` here: https://istio.io/latest/docs/tasks/security/authorization/authz-http/

That blocks auth until the later ALLOW AuthorizationPolicies allow it.

That mitigates no-authservice → authservice transitions. But doesn't mitigate failed keycloak (e.g. groups) reconfiguration. That's probably fine. Perhaps we could check claims with Istio for groups some day in the future if we really wanted to (also lets us claim better "zero trust", we'd validate groups at the workload too).

**Comment by mjnagel** [comment]
@bburky / @rjferguson21 I think the allow-nothing policy could be a viable addition, but only if opt-in / not by default.

I'm still not totally sure on the value/necessity. As identified this is really only relevant for no-authservice → authservice transitions. So an app that was previously publicly exposed fails to reconcile, post-failed-upgrade it continues to be publicly exposed. I think that's exactly what I'd expect, in fact I might be more confused as an end user if it failed and I was locked out of my app with no auth (explicitly a state I did not ask to be in before or during the upgrade). I think this is only relevant/useful if:
- Time is crucial, you need your app to be locked down immediately and don't care if you're locked out on failure. I'm not sure I see this as realistic but maybe its realistic enough to warrant an opt in here.
- You aren't paying attention to your `Package` CR status or your app 🙃 - if you're not watching then this protects you from not knowing that it wasn't working but that feels like more of an organizational problem and is hopefully only relevant is time is crucial back to ^ point.

I don't have any strong objection to adding this as an option but if we were to document something like this I'm unsure of when we would actually recommend it.

**Comment by bburky** [comment]
allow-nothing (scoped to authservice) is actually not a breaking change or anything, it should be safe to enable by default. If you're already adding ALLOW AuthorizationPolicy rules later (which we do for authservice) then nothing changes. This just protects the gap between beginning of reconcile to end of reconcile, and fails-closed with HTTP 403, which is a better error anyway. It's far less destructive than deleting resources.

I would suggest keeping the `selectors:` on the allow-nothing policy, without that it would affect other apps in the namespace.

Ideally it protect more than just no-authservice → authservice transitions (adding group validation to AuthorizationPolicy someday would help there too). The most realistic way for failure is a bad SSO config that the Keycloak API rejects, but there are others too.

We could probably put off solving this until some day in the future, and try to do allow-nothing more broadly than just authservice (without selectors). We really do already have the data from out netpols data to generate Layer 4 AuthorizationPolicies, we could autogenerate them someday.

**Comment by bburky** [comment]
Or, just move the authservice AuthorizationPolicy all the way to the beginning before `keycloak()`. I thought it depended on the client name, but I just realized that's not actually a keycloak-generated value, we know it from the config ahead of time, we should be able to do that whole apply early.

**Comment by rjferguson21** [comment]
I updated the [PR](https://github.com/defenseunicorns/uds-core/pull/804) to apply an `allow-nothing` policy immediately prior to Keycloak/Authservice methods. 

I ended up refactoring some of the policy building stuff so lots of stuff touched but the main functional change is - https://github.com/defenseunicorns/uds-core/pull/804/files#diff-a6165481bb49eafca7a35e539afc1ffc65d2f14549239a837dbebfbfda466ceaR71-R77.

It is currently enabled on by default but could make it opt-in like the previous implementation.

**Comment by rjferguson21** [comment]
After stewing on this for a bit we're closing this for the time being.  The scenarios where the current implementation meaningfully protects someone are pretty limited, specifically
* Package is deployed without authservice protection and then updates Package to include authservice protection but something (presumably keycloak or authservice fails).

While that is not nothing, I don't feel it justifies the changes introduced.  If we had a more general solution that accounted broadly for 'failing closed' that was not specifically targeted at Authservice I'd be  more enthused about introducing this kind of logic. 

Happy to reopen if there are scenarios I'm overlooking, or further discussion is warranted.
